project:
  type: website
  output-dir: ../../docs

website:
  title: "Gestión del dato urbano en Melbourne"
  description: "Análisis mediante Redes de Aprendizaje Profundo de Series Temporales Parcialmente Observadas sobre Datos de Ocupación de Estacionamiento en un Espacio Urbano Inteligente"
  navbar:
    logo: img/logoURJC.png
    left:
      - href: index.qmd
        text: Inicio
      - href: visualizations.qmd
        text: Análisis de datos
      - href: predictions.qmd
        text: Modelado y resultados  
      - href: references.qmd
        text: Bibliografía
    right:
      - icon: github
        href: https://github.com/PPardodatasc/PPG-TFG-URJC
        aria-label: Repositorio GitHub

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    lang: es